.\" Manpage for red.
.\" Contact nicolo.santamaria@gmail.com for bug reports.
.TH red 1 "10-02-2020" "red man page"

.SH NAME
red \- Recursive editor.

.SH SYNOPSIS
.B red [OPTIONS] "pattern" "replacement" filename

.SH DESCRIPTION
Red \- Recursive editor.
.P
Red is a fast and intuitive find & replace cli.
.P
Red replaces all matches of a specified regex with the provided replacement text.
.P
It can be run over single files or entire directories specified in the command line argument.
.P
When red encounters a directory it recursively finds and replaces text in all the files in the directory tree.

.SH OPTIONS
.B "-p"
    Print to stdout instead of writing each file.

.B "-v"
    Verbose, explain what is being done.

.B "-g"
    Add a glob the file names must match to be edited.

.B "-a"
    Includes hidden files (starting with a dot).

.B "-l"
    Max depth in a directory tree (default -1).

.B "-h"
    Prints the help message.

.SH AUTHOR
Nicolò Santamaria <nicolo.santamaria@gmail.com>
